### ISSUE TITLE
Request for per-timestamp regime codes

### ISSUE THREAD

**Issue by foabodo** [RomainLITUD/Car-Following-Dataset-HV-vs-AV#2]
In the interest of fitting a Wiedemann CF model to this data quickly, knowing the car-following regime at each time step would allow for parallelized rather than sequential computation. The data set's inclusion of the total seconds per instance that a vehicle was in a regime suggests that the regime per-timestamp is known, but it seems this information is missing.

**Comment by RomainLITUD** [comment]
Thank you, Franklin. We have this per-step regime information. We will add it very soon.

**Comment by foabodo** [comment]
Wonderful! thank you so very much. I think this data set will have a significant impact. I am also learning from your paper better ways to clean my own data.

Separately, I noticed that a small number of data points have accelerations larger in magnitude than the gravitational constant, which I think it the theoretical limit for acceleration and deceleration.

It's not an issue for me, I just thought it was noteworthy.

**Comment by RomainLITUD** [comment]
We have added the per-timestamp regime here, the full_regimes.zip. You can directly download it from this page. The updated dataset containing this zip is under preview on the 4.TU data platform. It will be available soon :)

**Comment by foabodo** [comment]
Hello. Thanks so much for taking the time to include this extra data.
