### ISSUE TITLE
Questions about the meaning of the data

### ISSUE THREAD

**Issue by dyq243478** [RomainLITUD/Car-Following-Dataset-HV-vs-AV#3]
It has been discovered that the three folders （CarFollowing,full_regimes_per_timestamp, and regimes） contain files named regimes_list_AH_train.csv with the same number of data but different values. What are the meanings of these three documents respectively

**Comment by RomainLITUD** [comment]
Hi,

The full_regimes_per_timestamp gives the car-following regime of each 0.1s time step. Regimes is a summary file, which gives the total time duration of each regime in every car-following pair.

Hope this helps.

**Comment by dyq243478** [comment]
This is very useful to me. Thank you very much for your answer！
